name: CI

on:
  pull_request: {}

jobs:
  test-1:
    name: Test 1
    runs-on: ubuntu-latest
    steps:
      - run: echo "success 1"


  test-2:
    name: Test 2
    runs-on: ubuntu-latest
    steps:
      - run: echo "success 2"


  test-3:
    name: Test 3
    runs-on: ubuntu-latest
    steps:
      - run: echo "fail 3"
      - run: exit 1


  Test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - test-1
      - test-2
      - test-3
    steps:
      - run: echo "success"
