name: CI

on:
  pull_request: {}

jobs:
  test-1:
    name: Test 1
    runs-on: ubuntu-latest
    steps:
      - run: echo "success 1"


  test-2:
    name: Test 2
    runs-on: ubuntu-latest
    steps:
      - run: echo "success 2"


  test-3:
    name: Test 3
    runs-on: ubuntu-latest
    steps:
      - run: echo "fail 3"
#      - run: exit 1


  Test:
    name: Test
    if: always()
    runs-on: ubuntu-latest
    needs:
      - test-1
      - test-2
      - test-3
    steps:
      - name: Test
        run: |
          echo FAILED_DEPENDENCY= $FAILED_DEPENDENCY
          [[ $FAILED_DEPENDENCY = true ]] && exit 1 || echo "Test executed"
        shell: bash
        env:
          FAILED_DEPENDENCY: ${{ contains(needs.*.result, 'failure') }}
      - run: echo "success"


  Test2:
    name: Test 2
    if: always()
    runs-on: ubuntu-latest
    needs:
      - test-1
      - test-2
      - test-3
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/check-needs
        with:
          failed-dependencies: ${{ contains(needs.*.result, 'failure') }}
